export const TMDB_POSTER_PATH_185x278 = 'https://image.tmdb.org/t/p/w185_and_h278_face'
export const TMDB_POSTER_PATH_138x175 = 'https://image.tmdb.org/t/p/w138_and_h175_face'
export const TMDB_POSTER_PATH_300x450 = 'https://image.tmdb.org/t/p/w300_and_h450_face'
export const TMDB_POSTER_PATH_45x45 = 'https://image.tmdb.org/t/p/w45_and_h45_face'
export const TMDB_BACKDROP_PATH = 'https://image.tmdb.org/t/p/w1400_and_h450_face'
export const TMDB_IMAGE_ORIGINAL = 'https://image.tmdb.org/t/p/original'
export const TMDB_POSTER_PATH_PLACEHOLDER = '/img/placeholder.jpg'
