export const TMDB_POSTER_PATH_185x278 = 'https://image.tmdb.org/t/p/w500'
export const TMDB_POSTER_PATH_138x175 = 'https://image.tmdb.org/t/p/w342'
export const TMDB_POSTER_PATH_300x450 = 'https://image.tmdb.org/t/p/w780'
export const TMDB_POSTER_PATH_45x45 = 'https://image.tmdb.org/t/p/w185'
export const TMDB_BACKDROP_PATH = 'https://image.tmdb.org/t/p/w1280'
export const TMDB_IMAGE_ORIGINAL = 'https://image.tmdb.org/t/p/original'
export const TMDB_POSTER_PATH_PLACEHOLDER = '/img/placeholder.jpg'
